M48
; DRILL file {KiCad 8.0.4} date 2024-09-19T20:08:31+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-19T20:08:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X44.0Y-125.0
X69.0Y-145.0
X119.0Y-125.0
X194.0Y-145.0
X267.0Y-123.0
M30
